version: '3.9'

# docker-compose down
# docker-compose up -d --build
# docker-compose up --build
# Update-Database -Context MainContext 

networks:
  app-backend:
    driver: bridge
  app-frontend:
    driver: bridge

services:

# APIS BEGIN -----------------------------------------------------------------------------

  api.admin.webapi:
    image: ${DOCKER_REGISTRY-}api.admin.webapi
    container_name: api.admin.webapi
    restart: always
    build:
      context: .
      dockerfile: backend/API.Admin/Dockerfile
    expose:
      - 5061
    ports:
      - 5061:5061
    links:
      - sqlserver
    networks:
      - app-backend
    depends_on:
      - sqlserver 

# APIS END -----------------------------------------------------------------------------

# DB BEGIN -----------------------------------------------------------------------------

  # SQL Server
  # Add-Migration Inicial -Context SqlServerDb
  # Update-Database -Context SqlServerDb
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    hostname: mssql
    container_name: sqlserver
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Poc2Minimal@Api
    networks:
      - app-backend
# -----------------------------------------------------------------------


# DB END -----------------------------------------------------------------------------

